### ISSUE TITLE
New version 0.8.8 does not work (profiles, and options invisible)

### ISSUE THREAD

**Issue by gwillegers** [dolohow/chrome-passwordmaker#2]
Yesterday I upgraded Firefox from version 56 to 59. Today I Passwordmaker Pro was upgraded from 0.8.5 to 0.8.8. When I opened the options, and under General Options checked the option to alphabetically sort the profiles, it did not sort. I closed the settings window. When I reopened Passwordmaker Pro all profiles where gone. I can not import profiles, set options, add a profile. The Options page only shows the five tabs (or buttons). None of them work, including Information.

I removed Passwordmaker Pro, restarted Firefox, added Passwordmaker Pro from the Mozilla store. Still the same: nothing works.

When I add version 0.8.5 it all works, and my profiles are still there. Reinstall 0.8.8 and everything is gone again. Reinstall 0.8.8 and it's all gone again.

**Comment by dolohow** [comment]
Yeah, I think I made one mistake.  Will try to fix it today.

**Comment by dolohow** [comment]
I released hotfix, check it now.  It's 0.8.8.1.

**Comment by gwillegers** [comment]
That was fast! Version 0.8.8.1 is working again.
