### ISSUE TITLE
Passwordmaker pro no longer working since Firefox update from version 65 to 66

### ISSUE THREAD

**Issue by gwillegers** [dolohow/chrome-passwordmaker#4]
After Firefox was updated from version 65 to version 66, Passwordmaker Pro is no longer working. The button on the toolbar has disappeared, alt-Z does not bring up Passwordmaker. No error messages are shown.

In the past after a Firefox update, the extensions were also invisible, but disable and the enable repaired that. This repair no longer works.

Why does Passwordmaker Pro not work in Firefox 66?

**Comment by dolohow** [comment]
I don't know, it works fine for me with `66.0.2`

**Comment by gwillegers** [comment]
Removing and reinstalling solved the problem.
